spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ypjs
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500

  jwt:
    secret: 31531513dgfodagklagnewjgneqjkfnjkqefnkjqkqkqsjajsdfaaaabbb

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

