
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ypjs
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        show_sql: true
        format_sql: true



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace